### PR TITLE
Updates to the startup files to work with collection-2019-3.0

### PR DESCRIPTION
**Pull request by mrakitin**
This was suggested by @mfuchsbnl during our today's work at FMX, as a temp workaround to the common Jupyter plotting issues.

cc @brunoseivam

### CODE REVIEW

**Comment by mrakitin** [comment]
Along the way, I discovered an old, know issue with pyepics 3.4 (which caused the profile to load forever), so I downgraded it to 3.3:
```
# conda install pyepics=3.3.0  -c https://conda.nsls2.bnl.gov/conda/nsls-ii-2019C3.0 -c https://conda.nsls2.bnl.gov/conda/defaults-2019C3.0 --override-channels
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda_envs/collection-2019-3.0-nyx

  added / updated specs:
    - pyepics=3.3.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyepics-3.3.0              |           py37_1         170 KB  https://conda.nsls2.bnl.gov/conda/nsls-ii-2019C3.0
    ------------------------------------------------------------
                                           Total:         170 KB

The following packages will be DOWNGRADED:

  pyepics                                      3.4.0-py37_1 --> 3.3.0-py37_1


Proceed ([y]/n)?


Downloading and Extracting Packages
pyepics-3.3.0        | 170 KB    | ##################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by mrakitin** [comment]
I created a new kernel to use the `collection-2019-3.0-nyx` conda environment, and the plotting works great with these minimally invasive changes:
image

**Comment by brunoseivam** [comment]
Looks good to me. If it works on their workstation, we can merge

**Comment by mrakitin** [comment]
Thanks, @brunoseivam! I've sent you an invitation to the org, so you should be able to merge.

**Comment by mrakitin** [comment]
I am merging it myself and will use the updates for a dual test (both `collection-2019-3.0.1` and `collection-2021-1.0`) in #5.

**Pull request merged**
